logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    initialization-mode: always
    initialize: true
    continue-on-error: true

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: false
      ddl-auto: none
      show-sql: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl